### ISSUE TITLE
[DONE] View/AutoComplete4 : Permission 부분 Class/Function 분리 완료

### ISSUE THREAD

**Issue by snowflake-1117** [kotlin-korea/AndroidApiDemo#3]
이번 과제 역시 코드가 굉장히 짧아서 큰 어려움 없이 변환을 진행할 수 있었습니다.
하지만 ~안드로이드 실력 역시 짧은 지라~ 의외의 부분에서 복병이 발생했네요.

문제(?)의 코드는 _AutoComplete4_(AutoComplete5 역시 비슷한 내용의 코드)입니다.
<br />

## AutoComplete4
이 코드는 1) 디바이스의 연락처에서 이름을 가져와 2) AutoCompleteTextView에 글자를 입력할 시 3) 해당 글자에 알맞는 이름을 자동완성으로 제공하는 기능을 수행합니다.
<br />
* 코틀린으로 자동 변환한 원본코드

```kotlin
public class AutoComplete4 extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.autocomplete_4);

        ContentResolver content = getContentResolver();
        Cursor cursor = content.query(Contacts.CONTENT_URI,
                CONTACT_PROJECTION, null, null, null);

        ContactListAdapter adapter = new ContactListAdapter(this, cursor);

        AutoCompleteTextView textView = (AutoCompleteTextView)
                findViewById(R.id.edit);
        textView.setAdapter(adapter);
    }

    // XXX compiler bug in javac 1.5.0_07-164, we need to implement Filterable
    // to make compilation work
    public static class ContactListAdapter extends CursorAdapter implements Filterable {
        public ContactListAdapter(Context context, Cursor c) {
            super(context, c);
            mContent = context.getContentResolver();
        }

        @Override
        public View newView(Context context, Cursor cursor, ViewGroup parent) {
            final LayoutInflater inflater = LayoutInflater.from(context);
            final TextView view = (TextView) inflater.inflate(
                    android.R.layout.simple_dropdown_item_1line, parent, false);
            view.setText(cursor.getString(COLUMN_DISPLAY_NAME));
            return view;
        }

        @Override
        public void bindView(View view, Context context, Cursor cursor) {
            ((TextView) view).setText(cursor.getString(COLUMN_DISPLAY_NAME));
        }

        @Override
        public String convertToString(Cursor cursor) {
            return cursor.getString(COLUMN_DISPLAY_NAME);
        }

        @Override
        public Cursor runQueryOnBackgroundThread(CharSequence constraint) {
            FilterQueryProvider filter = getFilterQueryProvider();
            if (filter != null) {
                return filter.runQuery(constraint);
            }

            Uri uri = Uri.withAppendedPath(
                    Contacts.CONTENT_FILTER_URI,
                    Uri.encode(constraint.toString()));
            return mContent.query(uri, CONTACT_PROJECTION, null, null, null);
        }

        private ContentResolver mContent;
    }

    public static final String[] CONTACT_PROJECTION = new String[] {
        Contacts._ID,
        Contacts.DISPLAY_NAME
    };

    private static final int COLUMN_DISPLAY_NAME = 1;
}
```
<br />

#### 문제상황
1. 코드를 살피기 전 에뮬레이터로 실행했지만, 해당 뷰에 접근하자마자 애플리케이션이 종료 되는 현상 발생
2. Logcat 창에서 READ_CONTACTS 에 관한 java.lang.SecurityException: Permission Denial 메세지를 봄. 
3. 안드로이드 6.0(API 23)부터는 앱 실행 중에 권한을 요청해야 한다는 것을 알게 됨
#### 해결과정
4. 연락처 읽기 권한을 얻기 위해 인터넷 문서 참조: [런타임에 권한요청 안드로이드 문서](https://developer.android.com/training/permissions/requesting.html?hl=ko), [Android Marshmallow Permission](http://mommoo.tistory.com/49), [안드로이드에서 동적권한 얻기](http://developer88.tistory.com/22) 
5. 사용자가 `권한을 줄 경우/ 주지 않을 경우/ 다시 보지 않기를 체크해 권한을 주지 않을 경우`의 코드를 추가
```kotlin
 override fun onRequestPermissionsResult(requestCode: Int,
                              permissions: Array<String>, grantResults: IntArray) {
        when (requestCode) {
            MY_PERMISSIONS_REQUEST_READ_CONTACTS -> {
                // If request is cancelled, the result arrays are empty.
                if (grantResults.isNotEmpty() && grantResults[0] ==
 PackageManager.PERMISSION_GRANTED) {
                    // permission was granted, yay! Do the
                    // contacts-related task you need to do.
                    autoCompleteContacts()
                } else {
                    // permission denied, boo! Disable the
                    // functionality that depends on this permission.
                    showRequestAgainDialog()
                }
                return
            }
        }// other 'case' lines to check for other
        // permissions this app might request
    }

    fun autoCompleteContacts(){
        val content = contentResolver
        val cursor = content.query(Contacts.CONTENT_URI,
                CONTACT_PROJECTION, null, null, null)
        val adapter = ContactListAdapter(this, cursor, 0)
        edit.setAdapter(adapter)
    }

    fun checkPermission() {
        // Here, thisActivity is the current activity
        if (ContextCompat.checkSelfPermission(this,
                Manifest.permission.READ_CONTACTS)
                != PackageManager.PERMISSION_GRANTED) {

            // Should we show an explanation?
            if (ActivityCompat.shouldShowRequestPermissionRationale(this,
                    Manifest.permission.READ_CONTACTS)) {

                // Show an expanation to the user *asynchronously* -- don't block
                // this thread waiting for the user's response! After the user
                // sees the explanation, try again to request the permission.
                ActivityCompat.requestPermissions(this,
                        arrayOf(Manifest.permission.READ_CONTACTS),
                        MY_PERMISSIONS_REQUEST_READ_CONTACTS)
            } else {

                // No explanation needed, we can request the permission.
                ActivityCompat.requestPermissions(this,
                        arrayOf(Manifest.permission.READ_CONTACTS),
                        MY_PERMISSIONS_REQUEST_READ_CONTACTS)

                // MY_PERMISSIONS_REQUEST_READ_CONTACTS is an
                // app-defined int constant. The callback method gets the
                // result of the request.
            }
        }
        else {
            autoCompleteContacts()
        }
    }

    /**
     * When user denied READ_CONTACTS permission than show this dialog for persuasion.
     */
    private fun showRequestAgainDialog(): Unit {
        val builder: AlertDialog.Builder = AlertDialog.Builder(this)
        builder.setMessage(R.string.autocomplete_4_showRequestAgainDialog)
        builder.setPositiveButton(R.string.autocomplete_4_setPositiveButton) {
            _, _ ->
            try {
                val intent: Intent = Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS)
                        .setData(Uri.parse("package:" + packageName))
                startActivity(intent)
            } catch (e: ActivityNotFoundException) {
                e.printStackTrace()
                val intent: Intent = Intent(Settings.ACTION_MANAGE_APPLICATIONS_SETTINGS)
                startActivity(intent)
            }
        }
        builder.setNegativeButton(R.string.autocomplete_4_setNegativeButton) {
            _, _ ->
            finish()
        }
        builder.create()
        builder.show()
    }
```
#### 결과
6. 주소록 권한을 허가할 경우 주소록에서 이름을 얻어와 자동완성하는 기능 성공적으로 수행. 그렇지 않을 경우 AlertDialog를 띄워 설정에서 권한 허용하게끔 유도.
<br />

#### 문제 상황
1. AutoCompleteTextView에 텍스트 입력 후 전체를 지우는 경우(빈칸이 되는 경우) 다음과 같은 exception 발생.(디바이스는 계속 run 상태로 중간에 종료되지는 않음)
```logcat
08-12 20:26:08.526 7535-7576/com.example.android.apis W/Filter: An exception occured during performFiltering()!
                                                                java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter constraint
                                                                    at com.example.android.apis.view.AutoComplete4$ContactListAdapter.runQueryOnBackgroundThread(AutoComplete4.kt:0)
                                                                    at android.widget.CursorFilter.performFiltering(CursorFilter.java:49)
                                                                    at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
```
2. non-null 추정되는 변수가 null 이기 때문에 이런 예외가 발생하므로 
-> 1과 관련한 문자열 null 문제가 아닐까 생각
[전체 코드 링크](https://github.com/snowflake-1117/AndroidApiDemo/blob/7d0d69d3573ea58bafe7d9b18083983f010425df/mobile/src/main/java/com/example/android/apis/view/AutoComplete4.kt)
~////// 진행중 //////~

**Comment by Pluu** [comment]
Permission 처리는 의외로 긴부분이랑 별도 체크 로직만 Class / Funtion으로 분리하는 방법도 권장합니다

**Comment by snowflake-1117** [comment]
#### 문제해결&결과
3. 디버깅을 통해 constraint가 입력받은 문자열을 전달하는 것을 알게 됨
4. constraint를 Nullable로 바꿈!
```kotlin
override fun runQueryOnBackgroundThread(constraint: CharSequence?): Cursor {
```

**Comment by snowflake-1117** [comment]
@Pluu 와ㅋㅋㅋㅋ 엄청 빠른 코멘트!!! Permission처리 부분 클래스랑 함수로 분리하라는 말씀 참고해서 수정해보겠습니다! 감사합니다~~

**Comment by snowflake-1117** [comment]
Permission 체그 로직 클래스/함수로 분리: [ContactPermission.kt](https://github.com/snowflake-1117/AndroidApiDemo/blob/3a276cf9865866c6789d35e1ceaf71b5c13746a7/mobile/src/main/java/com/example/android/apis/view/ContactPermission.kt)

`showRequestAgainDialog()`는 AutoComplete4, 5가 다른 스트링을 쓰기 때문에 + 다이얼로그 생성
 시 startActivity를 호출하기 때문에 기존 클래스에 그대로 작성
